fix issue with using draper outside of controller/view context
drapergem/draper pull request #927
Opened 2023-08-01 16:07 UTC by timdiggins

## Description

Replace ActionController::TestRequest with ActionController::TestRequest

because
1) soft deprecated
2) will cause very hard to predict/test failures with ActiveJob/Sidekiq/Rake tasks. see #926 

The current PR also drops support for rails < 6.0 
I think this is a good idea (especially as the tests that were dropped were written from a Rails 5.0 perspective, so are very outdated, and brittle) but open to discussion around this if there's any engagement on this PR.

## Testing

See #926 

## To-Dos

- [ ] tests: I have not done additional tests to prove the need for the PR as they are hard to implement and harder to maintain and wouldn't catch regressions in any case.
- [ ] documentation: unnecessary I think

## References
* [GitHub Issue 926](https://github.com/drapergem/draper/issues926)

fixes #926

2023-08-05 03:54 UTC, tovodeverett commented
I have no authority at all with Draper, so I'm sorry that I can't help with getting your PR approved.

I do have one comment - I found the first line of the Description to be rather confusing.

You wrote: "Replace ActionController::TestRequest with ActionController::TestRequest"
I think you may have meant to write, "Replace ActionController::TestRequest with ActionDispatch::TestRequest"

2024-03-13 14:00 UTC, mdudzinski commented
I can confirm this PR fixed the problem (that popped up after upgrading to rails 6.1) in my project. 

In my case it was:

```
NoMethodError: undefined method `parameters' for nil:NilClass

@_params ||= Parameters.new(request.parameters)

~/.gem/ruby/3.1.4/gems/actionpack-6.1.7.7/lib/action_controller/metal/strong_parameters.rb:1187:in `params'
```

2024-08-30 07:53 UTC, Alexander-Senko requested changes
:+1: for dropping support of Rails 5, but could we split it from the fix?

The reason is that support for older Rails & Ruby versions is far more complicated than that of the code changed in this PR. E.g. we still have a CI for Ruby 2.4 that's incompatible with Rails 6.

2024-08-30 07:53 UTC, Alexander-Senko commented on lib/draper/view_context/build_strategy.rb
> -          is_above_rails_5_1 ? ActionController::TestRequest.create(controller) : ActionController::TestRequest.create
Could we just add a line before as a fix for now?

```ruby
          return ActionDispatch::TestRequest.create if defined? ActionDispatch::TestRequest
```

2024-09-01 13:13 UTC, Alexander-Senko requested changes

2024-09-01 13:13 UTC, Alexander-Senko commented on lib/draper/view_context/build_strategy.rb
> -          is_above_rails_5_1 ? ActionController::TestRequest.create(controller) : ActionController::TestRequest.create
Perfect! Thank you for diving deeper into this 🙏

2024-09-01 13:13 UTC, Alexander-Senko commented on lib/draper/view_context/build_strategy.rb
> +            controller.request ||= new_test_request controller
Just a small thing: could we put it inline to make things even simpler?

```suggestion
            controller.request ||= ActionDispatch::TestRequest.create
```

2024-09-01 19:41 UTC, Alexander-Senko approved these changes
Thanks a lot for your contribution 🙏

2024-09-01 19:59 UTC, merged