Improved integration with Global ID
drapergem/draper pull request #928
Opened 2024-02-06 14:09 UTC by Alexander-Senko

## Description

Implementing `Decorator.find` improves compatibility with Global ID and allows one to use decorated objects in background jobs seamlessly.

## Testing

1. Decorate an object.
2. Serialize the decorated object with Global ID or pass it to a job.
3. Deserialize the object.
4. Check if it's the same one and is still decorated.

## To-Dos
- [x] tests
- [x] documentation

## References
* [GitHub Issue #663](https://github.com/drapergem/draper/issues/663)
* [GitHub Pull Request #817](https://github.com/drapergem/draper/pull/817)

2024-08-21 23:18 UTC, y-yagi requested changes
Could you rebase with the `master` and run CI?
I tried to run the test on my local with this PR, but some tests failed.

2024-09-01 03:41 UTC, y-yagi commented
@Alexander-Senko 
This patch itself looks good to me. But, why did you add  `4.0.3` tag to this PR?  This PR brings a little breaking change. I think it's not a good idea to introduce a breaking change in a patch version update.

2024-09-01 10:58 UTC, Alexander-Senko commented
> This patch itself looks good to me.

Thus, could you approve it, please?

> But, why did you add `4.0.3` tag to this PR?

I don't have a strict opinion on that. You can reattach it to a milestone you like. It does nothing for now except organizing the issues until we get access to the gem.

> This PR brings a little breaking change. I think it's not a good idea to introduce a breaking change in a patch version update.

I see it a bit differently — as a know bug, but not an official API 🤔 Patch releases may break hacks and workarounds if they don't follow official API, may not they?

2024-09-01 22:32 UTC, y-yagi commented
> I don't have a strict opinion on that. You can reattach it to whatever milestone you like. It does nothing for now except organizing the issues until we get access to the gem.
> I've just started organizing the issues and introduced new milestones. Any help on that is appreciated.

Thanks for your detailed explanation. I understand what the purpose.

> I see it a bit differently — as a know bug, but not an official API 🤔 Patch releases may break hacks and workarounds if they don't follow official API, may not they?

I don't think so. This is documented behavior, you have changed the document, right?
We shouldn't change the documented behavior in changing patch versions and minor versions(as we follows  the semantic versioning strictly).

2024-09-01 22:33 UTC, y-yagi approved these changes
LGTM!

2024-09-01 22:39 UTC, merged

2025-12-22 20:04 UTC, woodardj commented
💯 this was a breaking change, and needed louder callout in the Release Notes and a Minor (instead of patch) version number. Calls to `[decorated object with delegate_all].to_global_id` suddenly started returning the Decorator instead of the original Object.